import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import { useEffect } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    
    <html lang="en" className='dark'>
      <head>
      <Script src="theme.js" strategy='afterInteractive'/>
      
      </head>
      <body >{children}</body>
    </html>
  )
}
